//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDR_MENU                        101
#define IDI_MAIN                        102
#define IDR_ACCELERATOR                 103
#define IDD_VERSION                     104
#define IDD_LOG                         105
#define IDD_KEY                         106
#define IDD_SPEED                       107
#define IDD_CONNECT                     108
#define IDD_SOUND                       109
#define IDD_KOROKORO                    110
#define IDD_PAR                         111
#define IDD_MEM_DUMP                    112
#define IDD_DIRECTORY                   113
#define IDD_CLOCK                       114
#define IDD_CHAT                        115
#define IDD_FILTER                      116
#define IDD_CHEAT                       117
#define IDD_CHEAT_INPUT                 118
#define IDR_CHEAT_MENU                  119
#define IDD_TEXTVIEW                    120
#define ID_VSYNC                        122
#define ID_123                          123
#define ID_EXT                          124
#define IDC_LOG                         1000
#define IDC_LIST                        1000
#define IDC_CODE                        1001
#define IDC_ADD                         1002
#define IDC_1A                          1003
#define IDC_SKIP                        1003
#define IDC_DELETE                      1003
#define IDC_1B                          1004
#define IDC_FPS                         1004
#define IDC_1START                      1005
#define IDC_SKIP2                       1005
#define IDC_1SELECT                     1006
#define IDC_LIMITTER                    1006
#define IDC_1UP                         1007
#define IDC_FPS2                        1007
#define IDC_1DOWN                       1008
#define IDC_LIMITTER2                   1008
#define IDC_1LEFT                       1009
#define IDC_SHOWFPS                     1009
#define IDC_1RIGHT                      1010
#define IDC_2A                          1011
#define IDC_2B                          1012
#define IDC_DAT                         1012
#define IDC_2START                      1013
#define IDC_DAT2                        1013
#define IDC_2SELECT                     1014
#define IDC_2UP                         1015
#define IDC_SEARCH_NUM                  1015
#define IDC_2DOWN                       1016
#define IDC_HEX                         1016
#define IDC_2LEFT                       1017
#define IDC_DEC                         1017
#define IDC_2RIGHT                      1018
#define IDC_FAST                        1019
#define IDC_SAVE                        1020
#define IDC_SRAM                        1020
#define IDC_LOAD                        1021
#define IDC_NOSRAM                      1021
#define IDC_RAM1                        1022
#define IDC_AUTO                        1022
#define IDC_RAM2                        1023
#define IDC_PAUSE                       1023
#define IDC_NORAM                       1024
#define IDC_HIMEM                       1025
#define IDC_SERVER                      1026
#define IDC_SEARCH                      1026
#define IDC_CLIENT                      1027
#define IDC_BYTE                        1027
#define IDC_WORD                        1028
#define IDC_FWORD                       1029
#define IDC_DWORD                       1030
#define IDC_NORMAL                      1031
#define IDC_PROGRESS                    1032
#define IDC_MUCH                        1032
#define IDC_STATUS                      1033
#define IDC_DEST                        1033
#define IDC_START                       1034
#define IDC_ADDR                        1034
#define IDC_TERMINATE                   1035
#define IDC_ADDR2                       1035
#define IDC_SQ1                         1036
#define IDC_ONCE                        1036
#define IDC_SQ2                         1037
#define IDC_FOREVER                     1037
#define IDC_WAV                         1038
#define IDC_ADD_SEARCH                  1038
#define IDC_NOI                         1039
#define IDC_UNUSE                       1040
#define IDC_USE_ANALOG                  1041
#define IDC_KUP                         1042
#define IDC_KDOWN                       1043
#define IDC_KLEFT                       1044
#define IDC_KRIGHT                      1045
#define IDC_SPLIT                       1046
#define IDC_SENSITIVE                   1047
#define IDC_SKUP                        1048
#define IDC_SKDOWN                      1049
#define IDC_SKLEFT                      1050
#define IDC_SKRIGHT                     1051
#define IDC_SS                          1052
#define IDC_MY_ROM                      1053
#define IDC_ROM_SELECT1                 1054
#define IDC_TAR_ROM                     1055
#define IDC_ROM_SELECT2                 1056
#define IDC_SAVE_PATH                   1058
#define IDC_SAVE_DIR                    1059
#define IDC_DAY                         1060
#define IDC_HOUR                        1061
#define IDC_MIN                         1062
#define IDC_SEC                         1063
#define IDC_DISPLAY                     1066
#define IDC_MES                         1068
#define IDC_IPADDR                      1069
#define IDC_YOUR_IP                     1070
#define IDC_MEDIA_PATH                  1071
#define IDC_MEDIA_DIR                   1072
#define IDC_CMP_EQUAL                   1073
#define IDC_FFB                         1073
#define IDC_CMP_LESS                    1074
#define IDC_RR                          1074
#define IDC_CMP_LARGE                   1075
#define IDC_RG                          1075
#define IDC_LOOP                        1076
#define IDC_RB                          1076
#define IDC_RDIV                        1077
#define IDC_RDEF                        1078
#define IDC_GR                          1079
#define IDC_GG                          1080
#define IDC_SCROLL                      1081
#define IDC_GB                          1081
#define IDC_GDIV                        1082
#define IDC_ADDRESS                     1083
#define IDC_GDEF                        1083
#define IDC_MOVE                        1084
#define IDC_BR                          1084
#define IDC_CHEAT_SAVE                  1085
#define IDC_BG                          1085
#define IDC_CHEAT_READ                  1086
#define IDC_BB                          1086
#define IDC_ALL_CLEAR                   1087
#define IDC_BDIV                        1087
#define IDC_CHEAT_NAME                  1088
#define IDC_BDEF                        1088
#define IDC_OVER_RIDE                   1089
#define IDC_REAL                        1089
#define IDC_ADD_NAME                    1090
#define IDC_LCD                         1090
#define IDC_ECHO                        1091
#define IDC_LOWPASS                     1092
#define IDC_MASTER                      1093
#define IDC_NAME                        1117
#define IDC_VIEWHELP                    1121
#define IDC_PORT                        1125
#define ID_RESTORE_STATE                10117
#define ID_SAVE_STATE                   10118
#define IDC_MEMORY                      22063
#define ID_EXIT                         40001
#define ID_LOADROM                      40002
#define ID_LOADROM2                     40003
#define ID_VERSION                      40004
#define ID_FULLSCREEN                   40006
#define ID_SHOWLOG                      40007
#define ID_KEY                          40008
#define ID_SETTRACE                     40009
#define ID_RESET1                       40011
#define ID_RESET2                       40012
#define ID_SPEED                        40013
#define ID_CONNECT                      40017
#define ID_SOUND                        40018
#define ID_X1                           40021
#define ID_X2                           40022
#define ID_X3                           40023
#define ID_X4                           40024
#define ID_KOROKORO                     40026
#define ID_PAR                          40027
#define ID_MEM_DUMP                     40028
#define ID_DIRECTORY                    40030
#define ID_REALTIMECLOCK                40031
#define ID_BG                           40032
#define ID_WINDOW                       40033
#define ID_SPRITE                       40034
#define ID_RELEASE_1                    40039
#define ID_RELEASE_2                    40040
#define ID_SNAPSHOT                     40041
#define ID_SOUNDRECORD                  40042
#define ID_FILTER                       40045
#define ID_NOMEM_DUMP                   40046
#define ID_PAUSE                        40047
#define ID_MOVIE_START                  40049
#define ID_MOVIE_END                    40050
#define ID_MOVIE_PLAY                   40051
#define ID_MOVIE_PLAY_STOP              40052
#define ID_CHEAT                        40053
#define ID_CHEAT_SAVE                   40054
#define ID_CHEAT_LOAD                   40055
#define ID_CHEAT_EXIT                   40056
#define ID_ALL_DELETE                   40057
#define ID_MACHINE_GB                   40059
#define ID_MACHINE_GBC                  40060
#define ID_MACHINE_AUTO                 40061
#define ID_SURFACETYPE_1                40062
#define ID_SURFACETYPE_2                40063
#define ID_SURFACETYPE_3                40064
#define ID_PROCESS_REALTIME             40065
#define ID_PROCESS_NORMAL               40066
#define ID_PROCESS_IDLE                 40067
#define ID_PROCESS_HIGH                 40068
#define ID_PROCESS_BELOW_NORMAL         40069
#define ID_PROCESS_ABOVE_NORMAL         40070
#define ID_MACHINE_GBA                  40072
#define ID_DEFAULT_GBA                  40073
#define ID_TGBHELP                      41000
#define ID_ENVIRONMRNT                  48000
#define ID_SAVE_DMY                     49000
#define ID_LOAD_DMY                     49500

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40074
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
